import '../firebase_options.dart';

/// Configuration facts about the Firebase wiring.
///
/// This deliberately lives **outside** `firebase_options.dart`: that file is
/// generated by `flutterfire configure` and is overwritten wholesale every
/// time the command runs, so anything hand-written in it is lost. Keeping the
/// guard here means re-running the CLI can never silently delete it.
abstract final class FlowFirebase {
  /// The package the Android app ships under. The Firebase Android app must
  /// be registered against exactly this, or `google-services.json` will not
  /// match and the Google Services Gradle plugin fails the build.
  static const androidPackageName = 'com.wlftech.flow';

  /// Whether the generated config carries a real API key.
  ///
  /// Guards a checkout where `firebase_options.dart` was never generated (or
  /// was committed with a placeholder): Firebase accepts a bogus key at init
  /// and only rejects it on the first real call, so without this the first
  /// symptom is a user being told "Something went wrong" under a registration
  /// form they had no way of completing.
  static bool get isConfigured {
    final key = DefaultFirebaseOptions.android.apiKey;
    return key.isNotEmpty &&
        !key.startsWith('REPLACE') &&
        !key.contains('YOUR_API_KEY');
  }
}
